### ISSUE TITLE
Install error: in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by GrahamCobb** [pradels/vagrant-libvirt#575]
I tried following the installation instructions but am stuck on the `vagrant plugin install vagrant-libvirt` step.

I am running debian stretch.  I have never previously used vagrant.  I do, however, use libvirt VMs and wanted to experiment with using vagrant in my libvirt environment.

I installed vagrant using apt-get -- I have vagrant 1.8.1. And Ruby 2.3.

At the plugin installation step I get the following error:

```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```

**Comment by infernix** [comment]
Could you try purging the Debian vagrant package and installing from https://www.vagrantup.com/downloads.html?

It may be a packaging issue on the debian side - I'm running sid here with the upstream package and haven't seen this before..

**Comment by GrahamCobb** [comment]
That worked, using the upstream package (1:1.8.1).

I have reported the debian bug (#818237).

Thanks for the help.

**Comment by infernix** [comment]
Great, will close for now until we have some feedback from the Debian packager.

**Comment by perobertson** [comment]
I am running Fedora 23 with ruby 2.3.0 and just ran into the same issue. I decided to try out setting my to ruby 2.2.4 and trying `vagrant plugin install vagrant-libvirt`.  This time it worked.

**Comment by gwillem** [comment]
For Ubuntu 16.04, replacing with the upstream package works as well, thanks @infernix

**Comment by tmartinx** [comment]
I want to use Vagrant 1.8 from Ubuntu 16.04 and I am facing this problem too...   :-(

I'll stick with Vagrant from Ubuntu repos for now, I don't like to install packages from outside of distro's repositories, I hope that this will be fixed soon!

Reported on Launchpad as well:

https://bugs.launchpad.net/ubuntu/+source/vagrant/+bug/1562696

**Comment by infernix** [comment]
This was reported upstream here as well: mitchellh/vagrant/issues/6911 

Some digging points to what looks to be an issue with rubygems: https://github.com/rubygems/rubygems/commit/044b0e2685e4b219b013f1067d670918a48c1f62

Relabelling this, but the fix is still to install the upstream package (which bundles rubygems).

**Comment by BartVB** [comment]
This has been fixed in upstream.

In the meantime, here is a simple patch by Debian dev Christian Hofstaedtler for /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb :

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818237#28

This fixed the issue for me (a test install with Ubuntu 16.04).

**Comment by leifjohn** [comment]
I purged and reinstalled the upstream package - still getting this error!

**Comment by leifjohn** [comment]
For the patch, are you actually editing the bundler.rb file?

**Comment by leifjohn** [comment]
Found instructions here:

http://stackoverflow.com/questions/36811863/cant-install-vagrant-plugins-in-ubuntu-16-04/36991648#36991648

**Comment by leifjohn** [comment]
after applying the patch and running vagrant up I am getting this error now:

`==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:163:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:159:in `root'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:71:in `bundle_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:419:in `configure_gem_home'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:407:in `configure_gem_home_and_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:57:in `configure'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:118:in `definition'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
==> default: 	from /usr/bin/vagrant:75:in `<main>'
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_up'" returned a failed exit
code or an exception. The error output is shown below:

/usr/lib/ruby/vendor_ruby/bundler.rb:163:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler.rb:159:in `root'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:71:in `bundle_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:419:in `configure_gem_home'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:407:in `configure_gem_home_and_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:57:in `configure'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:118:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
	from /usr/bin/vagrant:75:in `<main>'
`

**Comment by ertay** [comment]
@leifjohn did you manage to fix that? I just ran into the same problem after patching the bundler.rb file. I can install plugins but vagrant up doesn't work.

**Comment by leifjohn** [comment]
@ertay I did get it to finally work but I can't remember how. I think I ended up completely removing (purging) things and installing them over again.

**Comment by DavidEBrumbaugh** [comment]
I had this error on ubuntu 16.04 (64 bit) on the latest upstream version of Vagrant (1.8.3).  When I purged that version and replaced it with 1.8.1 it worked.

**Comment by akeif** [comment]
Patch mentioned by @leifjohn works for me.

**Comment by rgrosset** [comment]
Patch mentioned by @leifjohn works for me too on Ubuntu 16.04 and Vagrant 1.8.1

**Comment by kenorb** [comment]
To quick-fix the issue, try this command:

    sudo sed -i'' "s/Specification.all = nil/Specification.reset/" /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb

to patch `bundler.rb` file.

**Comment by nawfalCode** [comment]
Updating Vagrant from 1.8.1 to 1.8.4 has fixed the problem. Thanks @infernix

**Comment by nexhub** [comment]
@kenorb quick fix is working. thx!
works at least for installation

**Comment by muelli** [comment]
JFTR: Here's the bug report for Ubuntu 16.04: https://bugs.launchpad.net/ubuntu/+source/vagrant/+bug/1562696

**Comment by RobQuistNL** [comment]
Huzaa for @kenorb - am now able to install plugins again. Running 16.04 and Vagrant 1.8.1. Thanks!

**Comment by JoseCage** [comment]
:+1:  @kenorb 

Works for me.. Thanks so much..

**Comment by vikcon** [comment]
I am using Vagrant 1.8.6, after patching bundler I got another error for nokogiri.

**Comment by mikeatlas** [comment]
Thanks @kenorb, your quick-fix helped me as well.

**Comment by davidsolorzano20** [comment]
@kenorb command 
sudo sed -i'' "s/Specification.all = nil/Specification.reset/" /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb
solved my problem.

**Comment by jonkelleyatrackspace** [comment]
sudo sed -i'' "s/Specification.all = nil/Specification.reset/" /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb

solved my problem too

**Comment by wanchic** [comment]
Ubuntu 16.04.1 LTS, installed Vagrant 1.8.7 (https://releases.hashicorp.com/vagrant/1.8.7/). This allowed me to install vagrant-libvirt.

**Comment by thnam91** [comment]
Thank you, @kenorb.

It works properly.

**Comment by wgyaxcal** [comment]
i edited 
```
    #@@stubs_by_name = specs.group_by(&:name)
    @@stubs_by_name = nil
```
and...
yeahh!!!!
```
➜ vagrant plugin install vagrant-hostmanager           
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.7)'!
```

i do know that it is a work around and i rolled it back, but this let me go ahead
install the plugin and 'vagrant up' works mostly well.

**Comment by RvKmR-WaGh** [comment]
Updating vagrant to 2.0.2 solved my issue 
Download latest vagrant from https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb?_ga=2.238967363.2132770154.1517759488-2123478237.1517759488

Steps to update vagrant:

ravikumar@ravikumar-RV409-RV509-RV709:~$ vagrant -v
Vagrant 1.8.1
ravikumar@ravikumar-RV409-RV509-RV709:~$ sudo dpkg -i Downloads/vagrant_2.0.2_x86_64.deb 
(Reading database ... 228270 files and directories currently installed.)
Preparing to unpack .../vagrant_2.0.2_x86_64.deb ...
Unpacking vagrant (1:2.0.2) over (1.8.1+dfsg-1) ...
Setting up vagrant (1:2.0.2) ...
Processing triggers for man-db (2.7.5-1) ...
ravikumar@ravikumar-RV409-RV509-RV709:~$ vagrant -v
Vagrant 2.0.2
